file_format: "1"
id: miryoku_mod
name: MIRYOKU_MOD
type: shield
url: https://github.com/irike1/miryoku_mod
requires: [nice_nano_v2]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - miryoku_mod_left
  - miryoku_mod_right