file_format: "1"
id: miryoku_mod
name: miryoku_mod
type: shield
url: https://github.com/irike1/miryoku_mod
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - miryoku_mod_left
  - miryoku_mod_right